FROM ubuntu:16.04
MAINTAINER Jeganathan Swaminathan <jegan@tektutor.org>

#ENV http_proxy http://10.20.30.40:8080
#ENV https_proxy https://10.20.30.40:8080

RUN apt-get -y update && apt-get -y install tree
