- name: Demonstrates use of our brand new custom add module
  hosts: localhost
  tasks:
   - name: Invoke the add custome module
     add: firstInput=100 secondInput=200
     register: output

   - name: Print the result
     debug: var=output
