---

- name: Configure nginx server in Ubuntu
  copy: src=default_ubuntu dest=/etc/nginx/sites-available/default
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
  notify:
    - Restart nginx web server in Ubuntu

- name: Configure nginx server in CentOS 
  copy: src=default_centos.conf dest=/etc/nginx/conf.d/default.conf
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
  notify:
    - Restart nginx web server in CentOS 
