---

- name: Install nginx server in Ubuntu
  apt: name=nginx state=present update_cache=yes
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

- name: Install epel-release package in CentOS 
  yum: name=epel-release state=latest
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

- name: Update packages in CentOS 
  yum: name=* state=latest
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

- name: Install nginx server in CentOS 
  yum: name=nginx state=present
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
