---
- name: Start the docker containers here
  hosts: localhost
  tasks:
   - name: Start the ubuntu containers
     docker_container:
        image: tektutor/ansible-ubuntu
        state: present
        name: "ubuntu{{item}}"
        ports:
          - "200{{item}}:22"
          - "800{{item}}:80"
     with_sequence: start=1  end=2
